### ISSUE TITLE
can't build 

### ISSUE THREAD

**Issue by lancerkind** [DDSSwiftTech/SwiftMine#10]
Hi,
I'll poke around more later, but I wanted to drop a line that: 
$ **make xcodeproj**
swift package generate-xcodeproj -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __info_plist -Xlinker MCHammer.plist -Xlinker -lc++ -Xlinker -lz -Xlinker -framework -Xlinker Foundation -Xswiftc -sdk -Xswiftc `xcrun -sdk macosx --show-sdk-path` -Xswiftc -target -Xswiftc x86_64-apple-macosx10.12.0 -Xcc -objc -Xcc -fobjc-arc -Xcc -DDLLX= -Xcc -DOS_MACOSX -Xcc -DLEVELDB_PLATFORM_POSIX -Xcc -DLEVELDB_ATOMIC_PRESENT -Xcc -x -Xcc objective-c++ -Xcc -std=c++14 -Xswiftc -import-objc-header -Xswiftc src/SwiftMineCore/include/SwiftMine-Bridging-Header.h
**error: the module at /Users/lancer/SwiftMine/src/leveldb does not contain any source files
fix: either remove the module folder, or add a source file to the module
make: *** [xcodeproj] Error 1
macattack:SwiftMine lancer$** 

I'm puzzled by this because leveldb has plenty of .cc files.  
I'm using High Serria and Xcode 8.

Maybe you could do a clean build and try the above on your own environment.

Cheers,
==>Lancer---

**Comment by dschwartz783** [comment]
Did you checkout recursively?

You should use:
git clone --recursive https://github.com/dschwartz783/SwiftMine.git
Although, this project is not yet complete, and does not work. I’ve been making some progress recently, but it needs work. Also make sure you’re on the dev branch. Master is useless at the moment. Once dev is working, I’ll move all development to master and delete it.

**Comment by dschwartz783** [comment]
New build rules. Should be easier now. Good luck!

**Comment by dschwartz783** [comment]
...and feel free to contribute! :D
